#!/usr/bin/env python3
import sys
import os
import helpers

from analyzer import Analyzer
from termcolor import colored

def main():
    if len(sys.argv) != 2:
        sys.exit("Usage ./tweets screen_name")
        
    
    #get tweets from helpers function
    tweets = helpers.get_user_timeline(sys.argv[1], 50)
    
    if tweets == None:
        sys.exit("Could not retreve tweets from {}".format(sys.argv[1]))
    
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    # score tweets
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored("{} {}".format(score, tweet) , "green" ))
        elif score < 0.0:
            print(colored("{} {}".format(score, tweet), "red"))
        else:
            print(colored("{} {}".format(score, tweet), "yellow"))
            
        
    
if __name__ == "__main__":
    main()
